[package]
name = "food-lib"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "Library and CLI for creating meal plans"
homepage = "https://github.com/notusknot/food"
repository = "https://github.com/notusknot/food"
readme = "../README.md"

[dependencies]
itertools = "0.10.3"
sqlite = "0.26.0"

[lib]
crate-type = ["cdylib"]
name = "food"
path = "src/lib.rs"

[[bin]]
name = "food"
path = "src/main.rs"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
