name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'src/'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check if formatting is good
      run: cargo fmt -- --check
    - name: Add clippy
      run: rustup component add clippy
    - name: Check if linting is good
      run: cargo clippy -- -D warnings
    - name: Check if it builds
      run: cargo build --verbose

